name: Rebuild

on:
  push:
    branches:
      - main # or the branch you want to trigger the workflow
  schedule:
    - cron: "*/2 * * * *" # Runs every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2" # specify the Ruby version your Jekyll site needs

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          GITHUB_TOKEN: ${{ secrets.Darling }}
          publish_dir: ./_site
